---
title: "HW4 Plotly"
author: "Alvin Jiao"
date: "2025-10-29"
output: html_document
---
## Load Instacart Dataset
```{r}
library(tidyverse)
library(plotly)
library(flexdashboard)
library(p8105.datasets)

# Load dataset
data("instacart", package = "p8105.datasets")
```

## Hitogram of orders by hour
```{r}
plot_ly(instacart,
x = ~order_hour_of_day,
type = "histogram",
nbinsx = 24,
hovertemplate = "Hour %{x}: %{y:,} items scanned<extra></extra>") |>
layout(xaxis = list(title = "Hour of Day (0–23)"),
yaxis = list(title = "Count"))

```

## Boxplot of Add-to-Cart Position by Reorder Status
```{r}
plot_ly(instacart,
x = ~as.factor(reordered),
y = ~add_to_cart_order,
type = "box",
boxpoints = "outliers",
hovertemplate = "Reordered = %{x}<br>Add-to-cart: %{y}<extra></extra>") |>
layout(xaxis = list(title = "Reordered (0 = first-time, 1 = reordered)"),
yaxis = list(title = "Add-to-Cart Position"))
```

## Scatterplot of Add-to-Cart Position vs Order Hour
```{r}
plot_ly(instacart,
x = ~order_hour_of_day,
y = ~add_to_cart_order,
type = "scatter",
mode = "markers",
marker = list(opacity = 0.2, size = 4),
hovertemplate = "Hour %{x}<br>Add-to-cart %{y}<extra></extra>") |>
layout(xaxis = list(title = "Hour of Day (0–23)"),
yaxis = list(title = "Add-to-Cart Position"))
```

